#pragma once
#include "AnimationIDs.h"

#pragma region PLANT_BBOX
#define BOOMERANG_BROTHER_BBOX_WIDTH 16
#define BOOMERANG_BROTHER_BBOX_HEIGHT 24
#define BOOMERANG_WIDTH 16
#define BOOMERANG_HEIGHT 18
#define BOOMERANG_BROTHER_SPEED 0.01f
#define BOOMERANG_SPEED 0.02f
#pragma endregion
#define ID_ANI_BOOMMERANG_BROTHER_L_TROWED 6100000
#define ID_ANI_BOOMMERANG_BROTHER_R_TROWED 6100010
#define ID_ANI_BOOMMERANG_BROTHER_L_TROWING 6100020
#define ID_ANI_BOOMMERANG_BROTHER_R_TROWING 6100030
#define ID_ANI_BOOMMERANG_L 6100040
#define ID_ANI_BOOMMERANG_R 6100050
#define ID_ANI_BOOMMERANG_TROW_L 6100060
#define ID_ANI_BOOMMERANG_TROW_R 6100070
#pragma region THE_STATE
#define BB_STATE_NO_HIT 100
#define BB_STATE_HIT_ONE 200
#define BB_STATE_DIE 300
#define BOOMERANG_STATE_NO_TROW_L 100
#define BOOMERANG_STATE_NO_TROW_R 110
#define BOOMERANG_STATE_TROWING 200
#define BOOMERANG_STATE_TROWED 300
#pragma endregion
#define BOOMERANG_COMEBACK 128
#define BOOMERANG_SNAP_COMEBACK 12
#define BOOMERANG_X_OFFSET 3
#define BOOMERANG_Y_OFFSET 3
constexpr float BOOMERANG_TROW_TIME = 50.0f;