#pragma once
#include "AnimationIDs.h"

#define ID_ANI_SUPER_LEAF_ITEM_LEFT ID_ANI_SUPER_LEAF_ITEM 
#define ID_ANI_SUPER_LEAF_ITEM_RIGHT ID_ANI_SUPER_LEAF_ITEM + 100 

//#define ID_ANI_SUPER_MUSHROOM_ITEM 2001000 
//#define ID_ANI_ONE_UP_MUSHROOM_ITEM 2002000 