#pragma once
#pragma region ITEM_BBOX
#define SUPER_LEAF_BBOX_WIDTH 16
#define SUPER_LEAF_BBOX_HEIGHT 14

#define MUSHROOM_BBOX_WIDTH 16
#define MUSHROOM_BBOX_HEIGHT 16
#pragma endregion

#pragma region SUPER_LEAF_ITEM
#define SUPER_LEAF_FALL_SPEED 0.025f
#define SUPER_LEAF_FALL_GRAVITY 0.000005f
#define SUPER_LEAF_SWAY_SPEED 0.005f
#define SUPER_LEAF_SWAY_AMPLITUDE 20.0f
#pragma endregion

#pragma region MUSHROOM_ITEM
#define MUSHROOM_RISE_DISTANCE MUSHROOM_BBOX_HEIGHT
#define MUSHROOM_GROW_WAIT_TIME 200
#define MUSHROOM_GROW_SPEED	0.025f

#define MUSHROOM_GRAVITY 0.002f
#define MUSHROOM_SPPED 0.15f
#pragma endregion

