#pragma once
#include "AnimationIDs.h"
#include "KoopaStateIDs.h"

#pragma region RED_KOOPA
// #define ID_ANI_RED_KOOPA 1000000
#define ID_ANI_RED_KOOPA_WALKING_LEFT				(ID_ANI_RED_KOOPA + 0)
#define ID_ANI_RED_KOOPA_WALKING_RIGHT				(ID_ANI_RED_KOOPA + 100)
#define ID_ANI_RED_KOOPA_SHELL_IDLE					(ID_ANI_RED_KOOPA + KOOPA_STATE_SHELL_IDLE)
#define ID_ANI_RED_KOOPA_SHELL_IDLE_OUT_TIME		(ID_ANI_RED_KOOPA + KOOPA_STATE_SHELL_IDLE_OUT_TIME)
#define ID_ANI_RED_KOOPA_SHELL_IDLE_OUT_TIME_HOLD	(ID_ANI_RED_KOOPA + KOOPA_STATE_SHELL_IDLE_OUT_TIME_HOLD)
#define ID_ANI_RED_KOOPA_SHELL_MOVE					(ID_ANI_RED_KOOPA + KOOPA_STATE_SHELL_MOVE)

#define ID_ANI_RED_KOOPA_PARATROOPA_LEFT			(ID_ANI_RED_KOOPA_TROOPA + 0)
#define ID_ANI_RED_KOOPA_PARATROOPA_RIGHT			(ID_ANI_RED_KOOPA_TROOPA + 100)
#pragma endregion

#pragma region GREEN_KOOPA
// #define ID_ANI_GREEN_KOOPA 1001000
#define ID_ANI_GREEN_KOOPA_WALKING_LEFT					(ID_ANI_GREEN_KOOPA + 0)
#define ID_ANI_GREEN_KOOPA_WALKING_RIGHT				(ID_ANI_GREEN_KOOPA + 100)
#define ID_ANI_GREEN_KOOPA_SHELL_IDLE					(ID_ANI_GREEN_KOOPA + KOOPA_STATE_SHELL_IDLE)
#define ID_ANI_GREEN_KOOPA_SHELL_IDLE_OUT_TIME			(ID_ANI_GREEN_KOOPA + KOOPA_STATE_SHELL_IDLE_OUT_TIME)
#define ID_ANI_GREEN_KOOPA_SHELL_IDLE_OUT_TIME_HOLD		(ID_ANI_GREEN_KOOPA + KOOPA_STATE_SHELL_IDLE_OUT_TIME_HOLD)
#define ID_ANI_GREEN_KOOPA_SHELL_MOVE					(ID_ANI_GREEN_KOOPA + KOOPA_STATE_SHELL_MOVE)

#define ID_ANI_GREEN_KOOPA_PARATROOPA_LEFT			(ID_ANI_GREEN_KOOPA_TROOPA + 0)
#define ID_ANI_GREEN_KOOPA_PARATROOPA_RIGHT			(ID_ANI_GREEN_KOOPA_TROOPA + 100)
#pragma endregion