#pragma once
#pragma region KOOPA_BBOX
#define KOOPA_BBOX_WIDTH 16
#define KOOPA_BBOX_HEIGHT 26

#define SHELL_BBOX_WIDTH 20
#define SHELL_BBOX_HEIGHT 16
#pragma endregion

#pragma region KOOPA_STATE
#define KOOPA_STATE_WALKING 0
#define KOOPA_STATE_SHELL_IDLE 200
#define KOOPA_STATE_SHELL_IDLE_OUT_TIME 210
#define KOOPA_STATE_SHELL_IDLE_OUT_TIME_HOLD 211
#define KOOPA_STATE_SHELL_MOVE 300

#define KOOPA_STATE_PARATROOPA 2000
#pragma endregion

#pragma region GREEN_KOOPA_STATE
#define GREEN_KOOPA_STATE_PARATROOPA_JUMP 3000
#define GREEN_KOOPA_STATE_PARATROOPA_WALK 3001
#pragma endregion

