#pragma once

#define KOOPA_GRAVITY 0.0005f
#define SHELL_GRAVITY 0.01f
#define KOOPA_WALKING_SPEED 0.05f
#define KOOPA_SHELL_SPEED 0.2f
#define KOOPA_PARATROOPA_ACCELERATION_Y 0.000075f

#define KOOPA_MAX_VY (KOOPA_PARATROOPA_ACCELERATION_Y * 1000.0f) // fly range
#define KOOPA_JUMP_VY (0.2f) // fly range

#define KOOPA_SHELL_TIMEOUT 3500
#define KOOPA_DIE_TIMEOUT 5500	