#pragma once

#include "AnimationIDs.h"

// #define ID_ANI_MARIO 0
#pragma region MARIO_ANIMATION
#define ID_ANI_MARIO_IDLE_RIGHT (ID_ANI_MARIO + 400)
#define ID_ANI_MARIO_IDLE_LEFT (ID_ANI_MARIO + 401)

#define ID_ANI_MARIO_WALKING_RIGHT (ID_ANI_MARIO + 500)
#define ID_ANI_MARIO_WALKING_LEFT (ID_ANI_MARIO + 501)

#define ID_ANI_MARIO_RUNNING_RIGHT (ID_ANI_MARIO + 600)
#define ID_ANI_MARIO_RUNNING_LEFT (ID_ANI_MARIO + 601)

#define ID_ANI_MARIO_JUMP_WALK_RIGHT (ID_ANI_MARIO + 700)
#define ID_ANI_MARIO_JUMP_WALK_LEFT (ID_ANI_MARIO + 701)

#define ID_ANI_MARIO_JUMP_RUN_RIGHT (ID_ANI_MARIO + 800)
#define ID_ANI_MARIO_JUMP_RUN_LEFT (ID_ANI_MARIO + 801)

#define ID_ANI_MARIO_SIT_RIGHT (ID_ANI_MARIO + 900)
#define ID_ANI_MARIO_SIT_LEFT (ID_ANI_MARIO + 901)

#define ID_ANI_MARIO_BRACE_RIGHT (ID_ANI_MARIO + 1000)
#define ID_ANI_MARIO_BRACE_LEFT (ID_ANI_MARIO + 1001)
#pragma endregion	

#define ID_ANI_MARIO_DIE (ID_ANI_MARIO + 999)

// #define ID_ANI_MARIO_SMALL 10000
#pragma region SMALL_MARIO_ANIMATION
#define ID_ANI_MARIO_SMALL_IDLE_RIGHT (ID_ANI_MARIO_SMALL + 1100)
#define ID_ANI_MARIO_SMALL_IDLE_LEFT (ID_ANI_MARIO_SMALL + 1102)

#define ID_ANI_MARIO_SMALL_WALKING_RIGHT (ID_ANI_MARIO_SMALL + 1200)
#define ID_ANI_MARIO_SMALL_WALKING_LEFT (ID_ANI_MARIO_SMALL + 1201)

#define ID_ANI_MARIO_SMALL_RUNNING_RIGHT (ID_ANI_MARIO_SMALL + 1300)
#define ID_ANI_MARIO_SMALL_RUNNING_LEFT (ID_ANI_MARIO_SMALL + 1301)

#define ID_ANI_MARIO_SMALL_BRACE_RIGHT (ID_ANI_MARIO_SMALL + 1400)
#define ID_ANI_MARIO_SMALL_BRACE_LEFT (ID_ANI_MARIO_SMALL + 1401)

#define ID_ANI_MARIO_SMALL_JUMP_WALK_RIGHT (ID_ANI_MARIO_SMALL + 1500)
#define ID_ANI_MARIO_SMALL_JUMP_WALK_LEFT (ID_ANI_MARIO_SMALL + 1501)

#define ID_ANI_MARIO_SMALL_JUMP_RUN_RIGHT (ID_ANI_MARIO_SMALL + 1600)
#define ID_ANI_MARIO_SMALL_JUMP_RUN_LEFT (ID_ANI_MARIO_SMALL + 1601)
#pragma endregion 