#pragma once
#include "AssetIDs.h"
#include "ActionIDs.h"

//constexpr int ID_SPRITE_MARIO 100000
constexpr int FLY_MARIO  = 1e7;
constexpr int BIG_MARIO = 1e4;
constexpr int SMALL_MARIO = 2e4;
constexpr int DIE_MARIO = 3e4;

#pragma region FLY_MARIO
#pragma endregion

#pragma region BIG_MARIO
// IDLE
constexpr int ID_SPRITE_MARIO_BIG = (ID_SPRITE_MARIO + BIG_MARIO);
constexpr int ID_SPRITE_MARIO_BIG_IDLE = (ID_SPRITE_MARIO_BIG + STATE_IDLE);
constexpr int ID_SPRITE_MARIO_BIG_IDLE_LEFT = (ID_SPRITE_MARIO_BIG_IDLE + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_BIG_IDLE_RIGHT = (ID_SPRITE_MARIO_BIG_IDLE + MOVE_RIGHT);

// WALING
constexpr int ID_SPRITE_MARIO_BIG_WALKING = (ID_SPRITE_MARIO_BIG + STATE_WALKING);
constexpr int ID_SPRITE_MARIO_BIG_WALKING_LEFT = (ID_SPRITE_MARIO_BIG_WALKING + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_BIG_WALKING_RIGHT = (ID_SPRITE_MARIO_BIG_WALKING + MOVE_RIGHT);

// RUNNING
constexpr int ID_SPRITE_MARIO_BIG_RUNNING = (ID_SPRITE_MARIO_BIG + STATE_RUNNING);
constexpr int ID_SPRITE_MARIO_BIG_RUNNING_LEFT = (ID_SPRITE_MARIO_BIG_RUNNING + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_BIG_RUNNING_RIGHT = (ID_SPRITE_MARIO_BIG_RUNNING + MOVE_RIGHT);

// JUMP
constexpr int ID_SPRITE_MARIO_BIG_JUMP = (ID_SPRITE_MARIO_BIG + STATE_JUMP);

constexpr int ID_SPRITE_MARIO_BIG_JUMP_WALK = (ID_SPRITE_MARIO_BIG_JUMP + JUMP_WALK);
constexpr int ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT = (ID_SPRITE_MARIO_BIG_JUMP_WALK + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT = (ID_SPRITE_MARIO_BIG_JUMP_WALK + MOVE_RIGHT);

constexpr int ID_SPRITE_MARIO_BIG_JUMP_RUN = (ID_SPRITE_MARIO_BIG_JUMP + JUMP_RUN);
constexpr int ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT = (ID_SPRITE_MARIO_BIG_JUMP_RUN + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT = (ID_SPRITE_MARIO_BIG_JUMP_RUN + MOVE_RIGHT);

// SIT
constexpr int ID_SPRITE_MARIO_BIG_SIT = (ID_SPRITE_MARIO_BIG + STATE_SIT);
constexpr int ID_SPRITE_MARIO_BIG_SIT_LEFT = (ID_SPRITE_MARIO_BIG_SIT + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_BIG_SIT_RIGHT = (ID_SPRITE_MARIO_BIG_SIT + MOVE_RIGHT);

// BRACE
constexpr int ID_SPRITE_MARIO_BIG_BRACE = (ID_SPRITE_MARIO_BIG + STATE_BRACE);
constexpr int ID_SPRITE_MARIO_BIG_BRACE_LEFT = (ID_SPRITE_MARIO_BIG_BRACE + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_BIG_BRACE_RIGHT = (ID_SPRITE_MARIO_BIG_BRACE + MOVE_RIGHT);
#pragma endregion


#pragma region SMALL_MARIO

// IDLE
constexpr int ID_SPRITE_MARIO_SMALL = (ID_SPRITE_MARIO + SMALL_MARIO);
constexpr int ID_SPRITE_MARIO_SMALL_IDLE = (ID_SPRITE_MARIO_SMALL + STATE_IDLE);
constexpr int ID_SPRITE_MARIO_SMALL_IDLE_LEFT = (ID_SPRITE_MARIO_SMALL_IDLE + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_SMALL_IDLE_RIGHT = (ID_SPRITE_MARIO_SMALL_IDLE + MOVE_RIGHT);

// WALKING
constexpr int ID_SPRITE_MARIO_SMALL_WALKING = (ID_SPRITE_MARIO_SMALL + STATE_WALKING);
constexpr int ID_SPRITE_MARIO_SMALL_WALKING_LEFT = (ID_SPRITE_MARIO_SMALL_WALKING + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_SMALL_WALKING_RIGHT = (ID_SPRITE_MARIO_SMALL_WALKING + MOVE_RIGHT);

// RUNNING
constexpr int ID_SPRITE_MARIO_SMALL_RUNNING = (ID_SPRITE_MARIO_SMALL + STATE_RUNNING);
constexpr int ID_SPRITE_MARIO_SMALL_RUNNING_LEFT = (ID_SPRITE_MARIO_SMALL_RUNNING + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT = (ID_SPRITE_MARIO_SMALL_RUNNING + MOVE_RIGHT);

// JUMP
constexpr int ID_SPRITE_MARIO_SMALL_JUMP = (ID_SPRITE_MARIO_SMALL + STATE_JUMP);
constexpr int ID_SPRITE_MARIO_SMALL_JUMP_WALK = (ID_SPRITE_MARIO_SMALL_JUMP + JUMP_WALK);
constexpr int ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT = (ID_SPRITE_MARIO_SMALL_JUMP_WALK + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT = (ID_SPRITE_MARIO_SMALL_JUMP_WALK + MOVE_RIGHT);

constexpr int ID_SPRITE_MARIO_SMALL_JUMP_RUN = (ID_SPRITE_MARIO_SMALL_JUMP + JUMP_RUN);
constexpr int ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT = (ID_SPRITE_MARIO_SMALL_JUMP_RUN + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT = (ID_SPRITE_MARIO_SMALL_JUMP_RUN + MOVE_RIGHT);

// SIT
constexpr int ID_SPRITE_MARIO_SMALL_SIT = (ID_SPRITE_MARIO_SMALL + STATE_SIT);
constexpr int ID_SPRITE_MARIO_SMALL_SIT_LEFT = (ID_SPRITE_MARIO_SMALL_SIT + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_SMALL_SIT_RIGHT = (ID_SPRITE_MARIO_SMALL_SIT + MOVE_RIGHT);

// BRACE
constexpr int ID_SPRITE_MARIO_SMALL_BRACE = (ID_SPRITE_MARIO_SMALL + STATE_BRACE);
constexpr int ID_SPRITE_MARIO_SMALL_BRACE_LEFT = (ID_SPRITE_MARIO_SMALL_BRACE + MOVE_LEFT);
constexpr int ID_SPRITE_MARIO_SMALL_BRACE_RIGHT = (ID_SPRITE_MARIO_SMALL_BRACE + MOVE_RIGHT);
#pragma endregion

constexpr int ID_SPRITE_MARIO_DIE = (ID_SPRITE_MARIO + DIE_MARIO);