#pragma once
#include "AssetIDs.h"
#include "ActionIDs.h"

//#define ID_SPRITE_MARIO 100000
#pragma region NORMAL_MARIO

#define BIG_MARIO 10000
#define SMALL_MARIO 20000
#define DIE_MARIO 30000

// IDLE
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + BIG_MARIO)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + STATE_IDLE)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + MOVE_LEFT)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + MOVE_RIGHT)

// WALING
#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + STATE_WALKING)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + MOVE_LEFT)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + MOVE_RIGHT)

// RUNNING
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + STATE_RUNNING)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + MOVE_LEFT)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + MOVE_RIGHT)

// JUMP
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + STATE_JUMP)

#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + JUMP_WALK)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + MOVE_LEFT)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + MOVE_RIGHT)

#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + JUMP_RUN)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + MOVE_LEFT)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + MOVE_RIGHT)

// SIT
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + STATE_SIT)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + MOVE_LEFT)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + MOVE_RIGHT)

// BRACE
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + STATE_BRACE)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + MOVE_LEFT)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + MOVE_RIGHT)
#pragma endregion


#pragma region SMALL_MARIO

// IDLE
#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + SMALL_MARIO)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + STATE_IDLE)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + MOVE_LEFT)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + MOVE_RIGHT)

// WALKING
#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + STATE_WALKING)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + MOVE_LEFT)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + MOVE_RIGHT)

// RUNNING
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + STATE_RUNNING)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + MOVE_LEFT)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + MOVE_RIGHT)

// JUMP
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + STATE_JUMP)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + JUMP_WALK)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + MOVE_LEFT)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + MOVE_RIGHT)

#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + JUMP_RUN)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + MOVE_LEFT)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + MOVE_RIGHT)

// SIT
#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + STATE_SIT)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + MOVE_LEFT)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + MOVE_RIGHT)

// BRACE
#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + STATE_BRACE)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + MOVE_LEFT)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + MOVE_RIGHT)
#pragma endregion

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + DIE_MARIO)